### ISSUE TITLE
Provide information about task properties at runtime

### ISSUE THREAD

**Issue by rbx** [FairRootGroup/DDS#110]
Give the user task a possibility to get a list of tasks properties and their read/write values.

**Comment by AnarManafov** [comment]
Extend key-value API with a method to return a list of keys, the given task depends on. Each key should be also associated with a flag, which says whether the key is r, w, or r/w. Probably the new method should return a map.

**Comment by AnarManafov** [comment]
DDS topology API (since DDS v2.4) provides this information now.
