### ISSUE TITLE
cmake wn_bin doesn't fail if dependency is missing

### ISSUE THREAD

**Issue by AnarManafov** [FairRootGroup/DDS#117]
When building wn_bin target, it analyses all dependencies and tries to copy depended libs into DDS worker package. When a lib is missing on the system, it doesn't fail.

~~~~
....
cp: /opt/local/lib/libboost_chrono-mt.dylib: No such file or directory
[100%] Built target wn_bin
~~~~

Expected result, the cmake configuration should fail.

**Comment by ktf** [comment]
Mmmm... I think the problem is that I have two installations, one on the system, and one using alibuild, which I pass via `-DBOOST_ROOT=$BOOST_ROOT`. Does DDS CMake actually honour that flag???

**Comment by AnarManafov** [comment]
yes, sure. We use standard cmake call, no custom attempts to search or something like that.
~~~~~
find_package(Boost 1.54 REQUIRED COMPONENTS  ${Boost_Components})
~~~

I also know, that standard find boost function files sometime to find the proper version. So I always recommend to explicitly define lib and include dirs for boost if there are multiple versions on the system.

But never the less, the wn_bin tag should fail explicitly if it can't find dependency for DDS worker package.

**Comment by ktf** [comment]
Failing is fine, still not clear to me why it picks up the wrong boost version. I will try to force `Boost_INCLUDE_DIR` and `Boost_LIB_DIR`.
