### ISSUE TITLE
Support for dynamic number of agents

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#122]
We now have a simple plugin which is able to communicate with the commander and we are indeed able to get notified when `onSubmit` with the number of requested agents. This is fine and we are now writing the code which makes mesos spawn the agents. 

However, this will mean that the number of agents is actually fixed by the command line, while I understood the general goal was to say "here is a topology, spawn as many agents as you can which allows the topology to run", i.e. agents would be created dynamically, depending on the topology. Am I missing something or this is not actually possible at the moment with the current plugin interface?

**Comment by AnarManafov** [comment]
You are absolutely right. This is why we also have onRequirements event handler.

But in general there will be two ways users call dds-submit:

   1: dds-submit -n/-c   -- where a fixed number of agents is requested. In this case they can play with the same DDS cluster using different topologies. By calling dds-topology --set/--stop. Also, be advised, that users can call dds-submit several times, like:
~~~~
dds-submit -n 10
dds-submit -n 4
~~~~
Will at the end produce 14 agents. DDS can dynamically accept and remove workers.

   2: dds-submit --topo <topology_file> in this case plug-in will be responsible to allocate agents according to the topology user requested. Also, in this case user would need to shutdown one topology to be able to play with other.

The second method is in the plan. But we don't want to rush implementing it. First we want to cover everything ALICE Online needs. This is mostly the first case.

**Comment by ktf** [comment]
Ok. For the moment we will simply implement the onSubmit part, that should already be a good enough demonstrator. 
BTW, IMHO, I think point (2) will be more popular (even in an online environment) than expected.

Anyways, as I said, we can for sure continue with 1.

**Comment by AnarManafov** [comment]
Reg. Online. I am not sure. The second way can be expensive with some plug-ins as they would need to shutdown old agents and deploy new one when user changes active topology.

**Comment by ktf** [comment]
I guess it depends on what you use as resource allocator, yes. With mesos the overhead should be minimal, hence my comment. Anyways, I agree with you, one step at the time.
