### ISSUE TITLE
dds-submit configuration file bug

### ISSUE THREAD

**Issue by kvnnap** [FairRootGroup/DDS#128]
This issue occurs whenever one tries to pass a configuration file to the mesos plugin.

When the following command is executed..

```
dds-submit -r mesos -c <path-to-config-file>
```

 ..and the configuration file does not have empty contents, the following error is displayed:
"error: Server reports: dds-ssh configuration: syntax error at line 1"

It seems that the SSH configuration syntax checker is being invoked although a different plugin is being used.

The following screenshot shows the problem:

![image](https://cloud.githubusercontent.com/assets/16206628/14342547/a9abbbac-fc9a-11e5-916d-c87dce69f1bf.png)

**Comment by AndreyLebedev** [comment]
This problem is fixed in the master branch.
