### ISSUE TITLE
make wn_bin on MacOS

### ISSUE THREAD

**Issue by helvihartmann** [FairRootGroup/DDS#134]
I have build boost with brew and when running >make wn_bin I get the error:

> ~/DDS-master/build $ make wn_bin
> [ 60%] Built target dds_protocol_lib
> [ 62%] Built target dds_user_defaults_lib
> [ 77%] Built target dds_intercom_lib
> [ 91%] Built target ddd-agent
> [ 97%] Built target ddd-user-defaults
> [100%] Generate WN binary package
> install: @loader_path/libboost_atomic-mt.dylib: No such file or directory
> ERROR: Can not build DDS worker package. Missing dependency.
> make[3]: *** [CMakeFiles/wn_bin] Error 1
> make[2]: *** [CMakeFiles/wn_bin.dir/all] Error 2
> make[1]: *** [CMakeFiles/wn_bin.dir/rule] Error 2
> make: *** [wn_bin] Error 2

with otool I get:

> ~/DDS-master/build $ otool -L /usr/local/lib/libboost_log.dylib 
> /usr/local/lib/libboost_log.dylib:
> 	/usr/local/opt/boost/lib/libboost_log.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	@loader_path/libboost_date_time.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	@loader_path/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	@loader_path/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	@loader_path/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

**Comment by AnarManafov** [comment]
Should be fixed in the current master.
