### ISSUE TITLE
DDS takes huge amount of RAM to compile

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#135]
Something in DDS can use up to 4GB of ram when building (I suspect something which has to do with the topology parser). Can this be looked at, please? It forces us to compile with -J1.

**Comment by AnarManafov** [comment]
I have tested on my OS X with clang. Each clang process takes at the top ~400 Mb.
So, if you have a slow machine with a low number of Mb on RAM, then adjust -j X according to your computing power. I believe you don't build ROOT with -j on any taking machine :) So, here the same.

For example on virtual machines we build with -j 2 only. But on my 3 years laptop I build with -j (unlimited).

I don't think we can fix anything here to dramatically change things. The code is pretty complex and uses many cutting edge stuff.
