### ISSUE TITLE
Build of master is broken

### ISSUE THREAD

**Issue by Barthelemy** [FairRootGroup/DDS#136]
I tried to build DDS with alibuild and I get this error : 
[100%] Generate WN binary package
cp: cannot stat 'not': No such file or directory
ERROR: Can not build DDS worker package. Missing dependency.
make[3]: *** [CMakeFiles/wn_bin] Error 1
make[2]: *** [CMakeFiles/wn_bin.dir/all] Error 2
make[1]: *** [CMakeFiles/wn_bin.dir/rule] Error 2
make: *** [wn_bin] Error 2

alidist branch : IB/v5-08/next

**Comment by AnarManafov** [comment]
I manage to reproduce this issue. This could happen when BOOST libs are not in the LD_LIBRARY_PATH. Make sure you set this variable with the BOOST path before building DDS.

**Comment by AnarManafov** [comment]
I have implemented the export, but it can only be used with cmake 3.2. At the moment DDS must support older versions of cmake. So, users therefore should export LD_LIBRARY_PATH with BOOST libs manually, which is, I think, is normal.
