### ISSUE TITLE
make install fails with current master

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#137]
Doing:

```
cmake $SOURCEDIR                                              \
      -DCMAKE_INSTALL_PREFIX=$INSTALLROOT                    \
      -DBOOST_ROOT=$BOOST_ROOT                 \
      -DBoost_DIR=$BOOST_ROOT                  \
      -DBoost_INCLUDE_DIR=$BOOST_ROOT/include

make wn_bin; make install
```

fails with:

```
242 CMake Error at cmake_install.cmake:53 (file):
243   file INSTALL cannot find
244   "/Users/ktf/work/active/sw/SOURCES/DDS/master/0/etc/version".
```

**Comment by ktf** [comment]
This is for 3019ff87ad86aebf4d7e2361068b973a79e1947a

**Comment by AnarManafov** [comment]
I can't reproduce this issue and I therefore guess, it is a user error.
DDS can dynamically recognize its version number using git (if the .git directory is present) or a version file.
DDS is supposed to be build using only two official ways:
- from a git clone. In this case .git directory is available and used to get the exact version of DDS including patch numbers.
or
- from the source tarball downloaded from the DDS website. In this case .git directory is not available, but a version file is present and used to get the exact version number.

In your case you probably try to build DDS from a git clone, but somehow removed .git directory. If this is the case, it is not supported way of building DDS.

Feel free to reopen if you used the official way to build DDS and it still doesn't work. I will investigate it more precisely.

**Comment by ktf** [comment]
Indeed we do a clone and remove the `.git`. It would be nice if this did not fail but it simply created a dummy version file.

**Comment by ktf** [comment]
(this is a new behaviour apparently, BTW, in the past it worked fine).

**Comment by AnarManafov** [comment]
I wouldn't like that. It will introduce an inconstancy. We won't be able to figure out the exact version of DDS and its patch numbers. Thus we will lose a way to trace down issues.

**Comment by AnarManafov** [comment]
It is not a new behavior. We use this method from very beginning. It worked before probably because there was with .git or version file available.

If you still want to have .git removed, then add a version file (kinda generate it on the fly before removing .git). The version is generated by this cmd:

~~~~~

execute_process(COMMAND git --git-dir "${CMAKE_SOURCE_DIR}/.git" describe --match "[0-9]*\\.[0-9]*" --abbrev=7 HEAD
                  COMMAND sed -e "s/-/./g"
                  OUTPUT_VARIABLE DDS_VERSION
                  OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process( COMMAND bash -c "echo \"${DDS_VERSION}\" > ${DDS_VERSION_FILE}" )
~~~~~

**Comment by ktf** [comment]
mmm... actually it's something else. I do have the `.git` directory. It also works fine with `1.1` tag, so I am puzzled.

**Comment by AnarManafov** [comment]
can you please execute this command:

~~~~
git --git-dir "${CMAKE_SOURCE_DIR}/.git" describe --match "[0-9]*\\.[0-9]*" --abbrev=7 HEAD
~~~~

this is how DDS recognizes its version during cmake configuration.

**Comment by ktf** [comment]
Bah, it works now.. Not sure what the problem was. Sorry for the noise.

--
Ciao,
Giulio
