### ISSUE TITLE
dds-agent: ignore commands if agent is in the idle state

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/DDS#155]
dds-agent has to ignore commands which has to be forwarded to the user task, i.e. custom commands and key-value updates, if it is currently is in the idle state (topology was stopped, user task crashes, user task done etc.).

**Comment by AnarManafov** [comment]
Implemented in the current master.
Intercom SM channels have now a drain-write-queue flag. It drains the queue on task exited and prevents any message to got through until another task is started.
