### ISSUE TITLE
dds-topology: check topology consistency before update

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/DDS#156]
In case of update from current to a new topology, tasks and collections with the same name has to stay unchanged in the new topology.
We do not support topology update if something was changed in the declaration task or collection.
New tasks and collections (with names that doesn't exist in the current topology) can be declared and added to the groups.

**Comment by AnarManafov** [comment]
The current DDS supports topology updates. If any declaration in the topology is changed, it will be update on the runtime env.
