### ISSUE TITLE
Mergers benchmark possible issues

### ISSUE THREAD

**Issue by Barthelemy** [FairRootGroup/DDS#158]
From Patryk :
> I also reproduced the problems with DDS - you can find in logs the case with 1001 agents (dds does not allow that), and with 501 agents where I have some problems with activating topology because of not enough agents running (I deployed 501 but after 10 minutes of waiting for initialization DDS is telling me that there is not enough agents).

Logs are attached : 
[dds_logs.zip](https://github.com/FairRootGroup/DDS/files/568460/dds_logs.zip)

**Comment by Barthelemy** [comment]
Anar : 

> Hi Patryk,

can you please repeat the test with 500 agents?

Once you submit agents, please use dds-info -n to verify that they are online. Checking the number of agents via “ squeue” is not sufficient. First of all, RMS always reports such commands with a delay, meaning that it could tell you that jobs are running, when in reality they went down couple of seconds ago.
On the other hand, DDS reports a real time info.

If you call “dds-topology —activate” and receive “The number of agents is not sufficient for this topology.” please call “dds-info -n” after that again.
Also, please send us slurm job output.

Another thing, are you sure that slurm worker nodes have outgoing connection open?
It can be that jobs are running, but agents are not able to connect back to the commander. 
You should run dds-commander server on the machine which is accessible by SLURM worker nodes.

As a test you can also gradually submit agents.
Like submit 100 gents, check that dds-info -n returns 100. Then again submit 100 and it should return 200 and so on. DDS can automatically join new agents to the previously running ones.
This way can help us identify the source of the problem.

All the best
Anar

**Comment by PatrykLesiak** [comment]
Dear All,

First of all, I am sure that slurm workers are (should be) able to connect to commander. PL-Grid infrastructure helpdesk told me that every computing nodes have physical connection with access machine which I am using (e.g. to run DDS commander).

I tried to deploy agents step by step. I think that this approach is much better than deploying 500 (501) agents at once. I 've repeated step by step deployment two times and it was working every time.
Here I have only one observation - I can see how many agents are deployed up to 400 agents using dds-info -n command. With 500 agents this command hangs and I cannot see the output (once I leaved the terminal for 10 minutes and after returning it was still hanging.

I've also repeated deployment of 501 agents at once. Unfortunately it was not working that good. After some time from agents deployment I tried to activate topology with 501 tasks and I got the message that number of agents is not sufficient.

You can find the logs here:
[logs.zip](https://github.com/FairRootGroup/DDS/files/568591/logs.zip)

**Comment by AnarManafov** [comment]
Patryk,  let's please try the following.

Remove your /net/people/plglesiak/.DDS directory and also ~/.DDS if they are different.
Build and Install the latest DDS master (should be 1.4), as you use a pretty old DDS build. 
In order to find the seed of the problem we have to use the most recent version of the software.

After that try submitting 500 jobs to your slum. Don't activate topology. Just call dds-info -n time to time Please mark time frames you get agents. Like how fast slurp starts your jobs. For example, mark 100 agents after X sec/min, mark 200 and so on ... util you get all 500 online or until the number stops to grow.  This is important to understand this behaviour. It could be related to the slurm not starting all your jobs in time.

Thanks for the help

**Comment by AnarManafov** [comment]
Patryk, please put the test on ice for a bit. Obviously we are facing here several issues missed together. In our tests we managed to reproduce the issue with dds-info hangs. Let us fix this first and then we continue from that point. I ping you when the patch in the master.

**Comment by AnarManafov** [comment]
Patryk, we only found one problem in dds-info, but nothing else. We've just tested with 400 and 500 agents - this is maximum of our available hardware resources. Everything works as expected.

The dds-info patch I have pushed to the master. So, use the current master as I suggested in previous comment. Please go ahead and continue the tests.

**Comment by PatrykLesiak** [comment]
Thank you Anar, 
I will install and test the newest version of DDS today evening. I will get back to you with results tomorrow.

**Comment by AnarManafov** [comment]
Sounds good, man. Thanks for your help.

**Comment by PatrykLesiak** [comment]
OK, so after installing the newest version I did not have any problems with deploying event 700 agents with "at once" approach. 700 agents were deployed after 2 minutes and this is much better result than with previous version of DDS.
Beside that I can see that still there is no possibility to deploy more than 1000 agents (sbatch: error: Batch job submission failed: Invalid job array specification).

**Comment by AnarManafov** [comment]
Thank you, Patryk, for the test. Glad the new version looks better in your tests. New version of DDS contains a lot of improvements.
