### ISSUE TITLE
Cannot deploy more than 1000 agents with SLURM plug-in

### ISSUE THREAD

**Issue by PatrykLesiak** [FairRootGroup/DDS#160]
It is impossible to deploy more than 1000 agents with SLURM plug-in because of error:

[plglesiak@login01 QC]$ dds-submit -r slurm -n 1001 -c My_SLURM.cfg
dds-submit: Contacting DDS commander on login01:20001 ...
dds-submit: Connection established.
dds-submit: Requesting server to process job submission...
dds-submit: Server reports: Creating new worker package...
dds-submit: Server reports: RMS plug-in: /net/people/plglesiak/DDS/1.5.3.gc519ff2/plugins/dds-submit-slurm/dds-submit-slurm
dds-submit: Server reports: Initializing RMS plug-in...
dds-submit: Server reports: RMS plug-in is online. Startup time: 49ms.
dds-submit: Server reports: Plug-in: Generating SLURM Job script...
dds-submit: Server reports: Plug-in: Preparing job submission...
dds-submit: Server reports: Plug-in: dds-submit-slurm-worker: Submitting DDS Job on the SLURM cluster...
dds-submit: Server reports: Plug-in: dds-submit-slurm-worker: Error: Failed to submit SLURM job (0)
dds-submit: Server reports: Plug-in: sbatch: error: Batch job submission failed: Invalid job array specification

dds-submit: error: Server reports: Plug-in: Failed to deploy agents

DDS log:
[log.zip](https://github.com/FairRootGroup/DDS/files/597102/log.zip)

**Comment by AnarManafov** [comment]
Patrick, I am afraid I can't reproduce this issue. I suspect, that it can be a limitation of your slurm system or your user account. To process the issue further I need additional info.

1. Can you please try to submit any simple script directly using "sbatch"?
In your job script use all options your have in your "My_SLURM.cfg" and also use "#SBATCH --array=1-1001"    
2. Additionally, can you please attach your My_SLURM.cfg and tar/zip the whole ~/.DDS/ directory.

**Comment by PatrykLesiak** [comment]
Dear Anar, 
I don't know if there is some problem on Prometheus cluster I am using. For a couple of days I was trying to run simple script as you suggested. The job is submitted but is in pending state for long time and do not turn into running. I sent a message to helpdesk to find out if there is some problem or maybe as you told some limitations. 
Nevertheless I ran job with DDS and here is the zip file with .DDS folder: https://drive.google.com/open?id=0B5YVquuOmb6nd3ctYjdQT0k2SEE
Here is the config file: 
[My_SLURM.cfg.txt](https://github.com/FairRootGroup/DDS/files/610057/My_SLURM.cfg.txt)

**Comment by PatrykLesiak** [comment]
Dear Anar, 
Sorry for the confusion, it occurred that indeed there is a limitation (1000 jobs) for Prometheus cluster which was not mentioned by helpdesk in an instruction.
Due to that reason I am closing the issue as it is not connected with DDS itself.
