### ISSUE TITLE
Error message about insufficient number of agents should say how many it needs

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#161]
`dds-topology --activate something.xml` fails with:

```
dds-topology: error: Server reports: The number of agents is not sufficient for this topology. 
```

as a user I would expect to have the required number of agents printed out and maybe even the command to increase their count.

**Comment by AnarManafov** [comment]
Agreed. I like this idea.
Something like (required/available X/Y)...

**Comment by ktf** [comment]
That would be perfect.
