### ISSUE TITLE
Inability to schedule should provide log of what happened.

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#162]
If I activate a topology with:

```
dds-topology --activate
```

I get:

```
dds-topology: Contacting DDS commander on grisu.dyndns.cern.ch:20001  ...
dds-topology: Connection established.
dds-topology: Requesting server to activate user tasks...
dds-topology: error: Server reports: Unable to schedule task <414806716141366186> with path main/groupFLP/flpSender
```

as a user I would expect a message saying what to do to debug the issue (e.g. "debug log can be found at XYZ")

**Comment by aphecetche** [comment]
+1 ;-)

**Comment by AnarManafov** [comment]
Can you please provide me with the "decltask" section of this task?
Also, send send me the full path of the executable (just as a string here).

Based on the given information we will tune this error message to be more user friendly.

**Comment by ktf** [comment]
The issue is the various:

```
    <declrequirement id="EPNReceiverHost">
        <hostPattern type="wnname" value="epn(00|01|02|03)"/>
    </declrequirement>
```

requirements which do not match. I would have expected a message:

```
Unable to schedule task <414806716141366186> with path main/groupFLP/flpSender.
Requirement `EPNReceiverHost` could not be satisfied.
```

this would have allowed me to fix the issue.

**Comment by AndreyLebedev** [comment]
This we could do. Thanks for pointing to this issue.
