### ISSUE TITLE
Build system leaves source directory dirty

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#182]
Hi,
after building DDS, the source directory contains additional generated files:

```
?? cmake/modules/DDS_CollectPrerequisitesGen.cmake
?? cmake/modules/DDS_CollectPrerequisitesGen.cmake.configured
?? etc/version
```

If it is not an option to write them to the build directory, I would recommend adding them to `.gitignore`. But IMHO - for the sake of reproducable builds - we should really not put temporary files in the source directory (are we sure they are regenerated every time they are required to be?).

Best regards,
Dennis

**Comment by AnarManafov** [comment]
Agree.
