### ISSUE TITLE
aliBuild fails while building DDS

### ISSUE THREAD

**Issue by tklemenz** [FairRootGroup/DDS#204]
Dear experts,

I am trying to compile O2 on a remote machine running CentOS 7.

The error occurs while building DDS. The DDS version is 2.0.

When I am logged in on the remote machine I am in a group called domänen-benutzer and apparently this leads to a problem while translating this name to UTF-8.

CMake Error: archive_write_header: Can't translate gname 'domänen-benutzer' to UTF-8
CMake Error: Problem creating tar: dds-wrk-bin-2.0-Linux-amd64.tar.gz

The full logfile and the output of ‘aliDoctor O2 --defaults o2’ can be found with the following link.

https://cernbox.cern.ch/index.php/s/JTObJGMz4uWjY3X 1

Thank you very much!
Best,
Thomas

**Comment by AnarManafov** [comment]
Hi @tklemenz,

I am afraid this is a cmake issue. I guess, something like this https://gitlab.kitware.com/cmake/cmake/issues/14934

I am not sure we will be able to fix it from our side. But I will have a look into it. Maybe there is a workaround.

**Comment by tklemenz** [comment]
Hi, thanks a lot for your reply. I'll look into that.

**Comment by yuanshiming** [comment]
Dear DDS experts,
I am trying to build Readout module, and also encountered an issue when building DDS, which reports:
"warning: cannot resolve item 'libgcc_s.so.1'"
The build log file can be found here: https://cernbox.cern.ch/index.php/s/XjroqtTfP3JC78i

**Comment by AnarManafov** [comment]
@yuanshiming , a couple of question to get a complete picture.
- Do you build BOOST on the same OS and with the same compiler as DDS?
- Do use alibuild or build all modules manually?

**Comment by yuanshiming** [comment]
> @yuanshiming , a couple of question to get a complete picture.
> 
> * Do you build BOOST on the same OS and with the same compiler as DDS?
> * Do use alibuild or build all modules manually?

Hi @AnarManafov ,

Yes, what I am trying to build is Readout module, using command: 
**aliBuild build ReadoutCard --defaults o2** 
boost 1.68.0 is built as a prerequisite.
and devtoolset-7 is enabled.

We tried to append 
	**string(REPLACE "::" ";" PREREQ_DIRS_LIST ${PREREQ_DIRS}::/opt/alisw/el7/GCC-Toolchain/v7.3.0-alice1-3/lib64::)**
in DDS_CollectPrerequisites.cmake, and looks like it's working now.

**Comment by AnarManafov** [comment]
Ok, got you.
In this case you can use the DDS_LD_LIBRARY_PATH environment variable before calling cmake on DDS.
Set this variable to the lib dir of you custom compiler.
