### ISSUE TITLE
Optimize disk usage with localhost plugin?

### ISSUE THREAD

**Issue by rbx** [FairRootGroup/DDS#210]
In FairMQ we are thinking about switching all of our device tests to use DDS for dynamic configuration.
First idea is to run DDS with the localhost plugin in this case.
One concern is the size of the working directories for each agent/task.
Running one of our examples that has 12 tasks with either ssh or localhost plugin, produces a working directory of over 2GB. Or around ~179MB per task:
![ssh-debug-fairmq-debug](https://user-images.githubusercontent.com/1915061/50002949-211af600-ffa2-11e8-8094-c917da958bd7.png)

After some experimentation I found that most of it comes from the fact that we compile DDS with debug symbols. Having a release build reduces the size to 20MB (or ~250MB for 12 tasks):
![ssh-release-fairmq-debug](https://user-images.githubusercontent.com/1915061/50003037-7f47d900-ffa2-11e8-9ff8-e181a285a79b.png)

The tests we need first of all during development, and during development we want to build ourselves and also our dependencies in debug mode. With DDS our test suite would launch many tens if not hundreds of tasks, which would lead to significant disk usage (and potentially decreased startup performance) on each test suite execution.

In any case, it would be nice if DDS was able to identify common files between tasks (at least for the localhost rms plugin) and share these between agents. This would benefit even for Release builds.

**Comment by dennisklein** [comment]
Why are these library and executable files copied at all?

**Comment by AnarManafov** [comment]
@dennisklein, by the design DDS doesn't distinguish between types of plug-ins. Therefore create the same, independent worker package for all RMS submissions.
But we are working to improve it and will get a special handling for the localhost plug-in.

**Comment by AnarManafov** [comment]
Implemented in the master
