### ISSUE TITLE
Introduce DDS_SESSION_ID environment variable (UI improvement)

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#213]
**Idea**: Have `dds-session start` define an environment variable `DDS_SESSION_ID` (or similar). If it is set, have all the other dds CLIs consume that environment variable alternative to the `-s,--session` argument.

**Rational**: At the moment we can either do [this](https://github.com/FairRootGroup/DDS/blob/master/res/tests/run_test_property.sh#L11-L13):
```bash
dds-session start
sessionID=$(dds-user-defaults --default-session-id)
```
,which is racing (bad), or we can do [that](https://github.com/FairRootGroup/DDS/blob/master/res/tests/run_test_index.sh#L13-L17):
```bash
output=$(dds-session start)
echo ${output}
sessionID=$(echo ${output} | grep "DDS session ID: " | cut -d' ' -f4)
```

In both cases, we need to pass `-s $sessionID` to all subsequent dds CLIs, which could optionally be saved, if they would consume an environment variable.

**Priority**: Low, Nice-to-have

**Comment by dennisklein** [comment]
After reconsideration I can live without this.

**Comment by AnarManafov** [comment]
@dennisklein, we still intend to implement it. We are too, after some reconsideration :), think it can be useful for CLI.

**Comment by AnarManafov** [comment]
@dennisklein, I am afraid, I wasn't able to find any portable/suitable way to implement this.

The dds-session command, if exports this variable, won't change anything in the parent shell. Therefore after command is done the variable will also gone.
The commander service won't help too.
I tried several other tricks/hacks, but didn't find any suitable solution.

If you have any idea on how we can implement this, feel free to re-open.

**Comment by dennisklein** [comment]
I agree, that the first part is not feasible. The only way this could be achieved, is, if the user would call `source dds-session start`, which looks unintuitive. So, it is probably best, if it stays like it is and the user explicitely defines this variable herself.

The second part would involve just very little change: All commands that currently accept `-s,--session` could be modified to read `DDS_SESSION_ID` from the environment, and if it exists and has a value, use it as a default value for the command line option, something like this:

```cpp
auto env_session_id = std::getenv("DDS_SESSION_ID");

if (env_session_id) {
  options.add_options()("session,s",
                         bpo::value<string>(&sessionID)->default_value(env_session_id),
                         "DDS Session ID (overrides any value in env var $DDS_SESSION_ID)");
  } else {
  options.add_options()("session,s",
                         bpo::value<string>(&sessionID)->required(),
                         "DDS Session ID (overrides any value in env var $DDS_SESSION_ID)");
}
```

Really just a little change, but may improve readability of user control scripts by a lot (sensible default, less explicit), at least in my opinion. I always try to read each command line like a short sentence and repeating `--session $DDS_SESSION_ID` on basically every line in the script felt distracting from the important action that happens on each particular line.

**Comment by dennisklein** [comment]
Compare

```bash
#!/usr/bin/env bash
cleanup() { dds-session stop $1 }
source ${DDS_ROOT}/DDS_env.sh
output=$(dds-session start)
export DDS_SESSION_ID=$(echo ${output} | grep "DDS session ID: " | cut -d' ' -f4)
trap “cleanup $DDS_SESSION_ID” EXIT
dds-submit -r localhost -n 5
dds-info --wait-for-idle-agents 5
dds-topology --activate my_topo.xml
fairmq-dds-command-ui -w RUNNING->READY
fairmq-dds-command-ui -c q!
dds-info --wait-for-idle-agents 5
dds-topology --stop
```

versus

```bash
#!/usr/bin/env bash
cleanup() { dds-session stop $1 }
source ${DDS_ROOT}/DDS_env.sh
output=$(dds-session start)
export DDS_SESSION_ID=$(echo ${output} | grep "DDS session ID: " | cut -d' ' -f4)
trap “cleanup $DDS_SESSION_ID” EXIT
dds-submit -s ${DDS_SESSION_ID} -r localhost -n 5
dds-info -s ${DDS_SESSION_ID} --wait-for-idle-agents 5
dds-topology -s ${DDS_SESSION_ID} --activate my_topo.xml
fairmq-dds-command-ui -s ${DDS_SESSION_ID} -w RUNNING->READY
fairmq-dds-command-ui -s ${DDS_SESSION_ID} -c q!
dds-info -s ${DDS_SESSION_ID} --wait-for-idle-agents 5
dds-topology -s ${DDS_SESSION_ID} --stop
```

**Comment by AnarManafov** [comment]
@dennisklein, it's implemented in the master. Now all commands will respect DDS_SESSION_ID, if defined.
Please try it and let me know if something is wrong.
