### ISSUE TITLE
Feature request: Easier way to setup the DDS environment when using the new Tools/Topology APIs

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#224]
**Affects**: [`2.5.5.g3aa26d5`](3aa26d5)
**Context**: Currently, the new Tools/Topology APIs seem to rely on a previously sourced `DDS_env.sh` script. To setup the DDS environment directly from our C++ program we use a helper function like this:
```cpp
     static auto LoadDDSEnv(const std::string& dds_location) -> void {
        // TODO upstream
        setenv("DDS_LOCATION", dds_location.c_str(), 1);
        setenv("HOME", CMAKE_CURRENT_BINARY_DIR, 1);
        std::string path(std::getenv("PATH"));
        path = DDS_BINDIR + std::string(":") + path;
        setenv("PATH", path.c_str(), 1);
        std::istringstream cmd;
        cmd.str("DDS_CFG=`dds-user-defaults --ignore-default-sid -p`\n"
                "if [ -z \"$DDS_CFG\" ]; then\n"
                "  dds-user-defaults --ignore-default-sid -d -c \"$HOME/.DDS/DDS.cfg\"\n"
                "fi");
        LOG(debug) << ">>>";
        for (std::string line; std::getline(cmd, line);) {
            LOG(debug) << " " << line;
        }
        LOG(debug) << ">>> " << std::system(cmd.str().c_str());
        LOG(debug) << "$HOME:               " << std::getenv("HOME");
        LOG(debug) << "$DDS_LOCATION:       " << std::getenv("DDS_LOCATION");
        LOG(debug) << "$PATH:               " << std::string(std::getenv("PATH")).substr(0, 80) << " ...";
    }
```

This obviously will not survive any future changes. As you can see, all only depends really on one argument `DDS_LOCATION`. A second part what we do here, is to set `HOME` to a different directory (CMake build dir here e.g.) to separate the DDS commander sandbox from the default sandbox at `$HOME/.DDS`.

**Feature Request**:
* **Part 1** Remove the need to source `DDS_env.sh` when using the C++ APIs and rely only `$DDS_LOCATION`. Because `CMAKE_INSTALL_PREFIX` is known at DDS build time, it could be used as a default value for `$DDS_LOCATION`. This will work, if one does not relocate the installation. The only package manager that relocates after installation (which installs DDS) is aliBuild, but they have a relocation logic that will catch it - I just verified:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a8c297a..5040106 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -341,7 +341,8 @@ endif(BUILD_dds_tools_lib)
 # Install
 #
 install(FILES ${DDS_MISC_FILES} DESTINATION .)
-install(PROGRAMS ${CMAKE_SOURCE_DIR}/etc/DDS_env.sh DESTINATION .)
+configure_file(etc/DDS_env.sh ${CMAKE_CURRENT_BINARY_DIR}/DDS_env.sh @ONLY)
+install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/DDS_env.sh DESTINATION .)
 # install bin files
 install(PROGRAMS ${DDS_BIN_FILES} DESTINATION bin)
 install(PROGRAMS ${DDS_BIN_PRIVATE_FILES} DESTINATION bin/private)
diff --git a/etc/DDS_env.sh b/etc/DDS_env.sh
index 17bc6fa..c72103a 100755
--- a/etc/DDS_env.sh
+++ b/etc/DDS_env.sh
@@ -16,12 +16,13 @@ create_dir()
 #=============================================================================
 # DDS Variables
 if [ "x${BASH_ARGV[0]}" = "x" ]; then
-    if [ ! -f DDS_env.sh ]; then
+    DDS_LOCATION="@CMAKE_INSTALL_PREFIX@"
+    if [ ! -f "${DDS_LOCATION}/DDS_env.sh" ]; then
         echo ERROR: must "cd where/DDS/is" before calling ". DDS_env.sh" for this version of bash!
         DDS_LOCATION=; export DDS_LOCATION
         return 1
     fi
-    DDS_LOCATION="$PWD"; export DDS_LOCATION
+    export DDS_LOCATION
 else
     # get param to "."
     THIS=$(dirname ${BASH_ARGV[0]})
```
results in an installed `DDS_env.sh` with the correct relocated install prefix:
```
╭─dklein@gamma ~/alice/DDS ‹ruby-2.6.0› ‹7499753*›
╰─➤  grep 'DDS_LOCATION="' ../sw/fedora30_x86-64/DDS/7499753bde-1/DDS_env.sh
    DDS_LOCATION="/home/dklein/alice/sw/fedora30_x86-64/DDS/7499753bde-1"
```
---
* **Part 2** Add a new environment variable, e.g. `$DDS_CONFIG_HOME` or `_LOCATION` or similar, that uses `$HOME/.DDS` as default value. That way, it would be possible to steer just the DDS commander sandbox location without breaking other functionality relying on `$HOME` one might use in the same environment.

**Comment by AnarManafov** [comment]
We need to use DDS_env.sh mostly to be able to export library paths.
DDS internally, behind the scenes, spawns child processing.
The problem is that on mac os, for example, a script can't propagate library paths to a child process. Therefore the path should be exported in the environment above parents one.

DDS is a cross platform solututiuion. For a user's convenience we prefer to use the same workflow for all platforms. Therefore the env script is a required first step.

> Spawning children processes of processes restricted by System Integrity Protection, such as by
> launching a helper process in a bundle with NSTask or calling the exec(2) command, resets the
> Mach special ports of that child process. Any dynamic linker (dyld) environment variables, such
> as DYLD_LIBRARY_PATH, are purged when launching protected processes.
> See more: https://forums.developer.apple.com/thread/9233


If you have a solution for that, let us know.

**Comment by dennisklein** [comment]
> > Spawning children processes of processes restricted by System Integrity Protection, such as by
> > launching a helper process in a bundle with NSTask or calling the exec(2) command, resets the
> > Mach special ports of that child process. Any dynamic linker (dyld) environment variables, such
> > as DYLD_LIBRARY_PATH, are purged when launching protected processes.
> > See more: https://forums.developer.apple.com/thread/9233
> 
> If you have a solution for that, let us know.

We could burn `RUNPATH` entries on Linux and `RPATH` on mac. This way one does not need the `(DY)LD_LIBRARY_PATH` at all in most cases. CMake has a [switch](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_RPATH_USE_LINK_PATH.html) for that but I have not tried it with DDS yet. See https://github.com/FairRootGroup/FairRoot/commit/389412c8de0ee053661d967bb4e5dfa53288d470#diff-af3b638bc2a3e6c650974192a53c7291 for a more complete example.

If the other aspects beside configuring the dynamic loader could be achieved via some API, too, we could avoid sourcing `DDS_env.sh` for programs that use DDS APIs.

If you are open to this idea, I could prepare a prototype as a starting point for what I have in mind.

**Comment by AnarManafov** [comment]
Hey @dennisklein ,

this sounds good. But we would need to build two types of binaries, or at least build them as relocatable.
Because we also use the same binaries on workers nodes, which don't have access to the DDS install folder.

I believe the ticket is not a priority and we can keep this ticket open and look into it again sometime later. Once the whole situation with the CS prototype is relaxed.
Please don't waste your time on it. I guess, you have enough work with your project along.
