### ISSUE TITLE
Investigate: agent stay on commander exit

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/DDS#279]
In some very rear cases when commander exits some agents stay. It seems that they don't receive the shutdown command and don't properly react on disconnect from the commander.

**Comment by AnarManafov** [comment]
There are cases when the agent runs out of free threads and therefore is not able to process neither disconnect events nor any command from the commander.
The place in the code and the reason is known. Looking for a proper solution...

**Comment by AndreyLebedev** [comment]
Fixed in the master.
