### ISSUE TITLE
dds-agent/src/CommanderChannel.cpp:1125:80: error: '_1' was not declared in this scope (Boost.173)

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#305]
Affects **DDS 3.2** on
| OS | Compiler | Boost | Logs |
| --- | --- | --- | --- |
| Fedora Rawhide (33) | `gcc 10.1.1` | `1.73` | [build](https://download.copr.fedorainfracloud.org/results/dklein/FairMQ/fedora-rawhide-x86_64/01434030-dds/build.log.gz), [env](https://download.copr.fedorainfracloud.org/results/dklein/FairMQ/fedora-rawhide-x86_64/01434030-dds/root.log.gz) |

**Error**:
```
[ 62%] Building CXX object dds-tools-lib/CMakeFiles/dds_tools_lib.dir/src/ToolsProtocol.cpp.o
/builddir/build/BUILD/DDS-3.2/dds-agent/src/CommanderChannel.cpp: In member function 'bool dds::agent_cmd::CCommanderChannel::on_cmdUSER_TASK_DONE(dds::protocol_api::SCommandAttachmentImpl<dds::protocol_api::cmdUSER_TASK_DONE>::ptr_t, dds::protocol_api::SSenderInfo&)':
/builddir/build/BUILD/DDS-3.2/dds-agent/src/CommanderChannel.cpp:1125:80: error: '_1' was not declared in this scope
 1125 |                        boost::bind(&SSlotInfo::container_t::value_type::first, _1));
      |                                                                                ^~
```

**Comment by AnarManafov** [comment]
Thanks, @dennisklein. Looks good!
Before I merge it I want to setup another build machine where we can also reproduce such issues. I want to reflect your environment.

**Comment by AnarManafov** [comment]
@dennisklein , thanks once again for the report. Should be fixed in the master now.
I will also look into a general fix for global placeholders, which have changed their policy in boost 1.73
