### ISSUE TITLE
Install Version.h and implement --version argument

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/DDS#342]
- [x] Install `Version.h` to `include/dds`
- [x] Implement `--version` argument for all executables (same as --help)
- [ ] `--help` and `--version` should work without a configuration file

**Comment by fuhlig1** [comment]
"--help" and "--version" should work without a configuration file

```
/home/uhlig/host/fairsoft/nov20/spack/opt/spack/linux-debian10-x86_64/gcc-8.3.0/dds-3.5.4-5ffidfrphpvjqgdnyqy65tmgjc24wfoz/bin/dds-info --help
[2021-02-10 10:38:34.324083] [0x00007f96ed6f7780] [info]    Could not open a DDS configuration file: 
```
