### ISSUE TITLE
Possible C++17 modernisation of `EnvProp.h`

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#368]
In a private discussion between @mattkretz and myself on how one could write the code in [`EnvProp.h`](https://github.com/FairRootGroup/DDS/blob/master/MiscCommon/EnvProp.h) with the new language features available in C++17, @mattkretz created the following example: https://godbolt.org/z/edobe1ocT. I personally find the example too interesting for code maintainability/readability aspects to not share it with you.

**Comment by AnarManafov** [comment]
@dennisklein , I agree. Looks like it. 
In our case we have 3 types to convert, not just 2. But it's not difficult to extend the example to support multiple types.
Thanks. I am looking into it.
