### ISSUE TITLE
Feature request: Add option for file mask of log files

### ISSUE THREAD

**Issue by davidrohr** [FairRootGroup/DDS#389]
We need to control the file mask of the stdout and stderr log files created by DDS fir akk process. Could this be added as a configuration option somewhere?

**Comment by AnarManafov** [comment]
@davidrohr , DDS has learned a new global option: agent.access_permissions

The option can be changed via DDS configuration (DDS user defaults).

This option forces the given file mode on agent side files.
At the moment the access permissions are applied only on user task log files (stdout and stderr).
Mode can be specified with octal numbers.
0400 - Read by owner
0040 - Read by group
0004 - Read by world
0200 - Write by owner
0020 - Write by group
0002 - Write by world
0100 - execute by owner
0010 - execute by group
0001 - execute by world
To combine these, just add the numbers together:
0444 - Allow read permission to owner and group and world
0777 - Allow everyone to read, write, and execute file

Default value is 0660.  
You will be  able to use this option once @AndreyLebedev  deploys the latest version of DDS on ALICE cluster.

**Comment by davidrohr** [comment]
Thx a lot, should be exactly what we need

Kind Regards
David Rohr

Sent from my mobile. (Excuse the typos!)

On September 6, 2021 5:04:16 PM GMT+02:00, Anar Manafov ***@***.***> wrote:
***@***.*** , DDS has learned a new global option: agent.access_permissions
