### ISSUE TITLE
SLURM plug-in: replace the deprecated "--workdir" argument

### ISSUE THREAD

**Issue by AnarManafov** [FairRootGroup/DDS#408]
As @rbx  has noticed, the "--workdir" argument for the sbatch command is deprecated. It should be replaced with "--chdir".

> Hi Anar,
there seems to have been change with the sbatch command line option, I think the plugin in DDS has to be updated
here is the error message:
 dds-submit -r slurm -n 1 --slots 1 -c /home/rbx/slurm.cfg                                                                                          2022-01-24 | 10:27:22
dds-submit: Connection established.
dds-submit: Requesting server to process job submission...
dds-submit: Server reports: Creating new worker package...
dds-submit: Server reports: RMS plug-in: /home/rbx/dev/DDS/install/plugins/dds-submit-slurm/dds-submit-slurm
dds-submit: Server reports: Initializing RMS plug-in...
dds-submit: Server reports: RMS plug-in is online. Startup time: 6ms.
dds-submit: Server reports: Plug-in: Generating SLURM Job script...
dds-submit: Server reports: Plug-in: Preparing job submission...
dds-submit: Server reports: Plug-in: dds-submit-slurm-worker: Submitting DDS Job on the SLURM cluster...
dds-submit: Server reports: Plug-in: dds-submit-slurm-worker: Error: Failed to submit SLURM job (0)
dds-submit: Server reports: Plug-in: sbatch: unrecognized option '--workdir=/home/rbx/.DDS/sessions/50afc10b-47da-46d1-b44d-81d2ebe12c39/50afc10b-47da-46d1-b44d-81d2ebe12c39/2022-01-24-10-27-58'
Try "sbatch --help" for more information
dds-submit: error: Server reports: Plug-in: Failed to deploy agents
dds-submit: error: Submission has Failed
I searched DDS source for --workdir and replaced it with --chdir, which is the actual option now and then it works.
11:41 AM
I checked Virgo and O2 farms, sbatch on both farms only has --chdir, no --workdir

>so, it looks like on virgo --workdir still works, but it is undocumented:
orybalch@lxbk0595:~ > sbatch -h | grep work
  -D, --chdir=directory       set working directory for batch script
                              energy, lustre, network or task
the error message above is from my own machine, which has a newer version
https://github.com/SchedMD/slurm/commit/9118a41e13c2dfb347c19b607bcce91dae70f8c6
1:15 PM
--workdir is deprecated, should be safe to replace with --chdir.

**Comment by AnarManafov** [comment]
sbatch v17.11 still supports "--workdir", but doesn't support "--chdir". I am trying to find out when they switched to "--chdir" to adjust the DDS plug-in accordingly.

**Comment by AnarManafov** [comment]
I think, I found it:
~~~
From the NEWS file:

* Changes in Slurm 17.11.0rc1
==============================
[...]
 -- Change --workdir in sbatch to be --chdir as in all other commands (salloc,
    srun).
~~~

**Comment by rbx** [comment]
Just FYI - this issue is also present on the EPN farm, they version does not have `--workdir` anymore.

**Comment by rbx** [comment]
Sounds good, thanks!

**Comment by rbx** [comment]
Tested newest version, there is still --workdir present.
I think it needs to be changed here also: https://github.com/FairRootGroup/DDS/blob/master/plugins/dds-submit-slurm/src/job.slurm.in#L6

**Comment by AnarManafov** [comment]
Thank you, @rbx. Fixed now.
