### ISSUE TITLE
DDS topology: Add custom requirement type for tasks and collections

### ISSUE THREAD

**Issue by AnarManafov** [FairRootGroup/DDS#445]
@rbx needs a possibility to specify custom requirements for tasks and collections.
He wants to access them via DDS Topology API.
In the future either DDS itself or possible plug-ins might be able to benefit from custom requirements too.

Example of the definition:
~~~~
<declrequirement type="custom" name="myname" value="myvalue"/>
~~~~

**Comment by rbx** [comment]
Here are some examples of how such a requirement could be used by a topology controller, to attach/extract requirements to tasks/collections.
- Require a certain number of working collections/tasks, before aborting a running topology:
```xml
<declrequirement type="custom" name="nmin" value="25"/>
```
- Allow task/collection to fail, without aborting a running topology:
```xml
<declrequirement type="custom" name="expendable" value="true"/>
```
- Require specific number of cores for task/collection:
```xml
<declrequirement type="custom" name="ncores" value="10"/>
```
