### ISSUE TITLE
C++20 support

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#477]
In the upcoming jan24 release of FairSoft we are aiming to start supporting the compilation with C++20 (default is still C++17). Currently, FairSoft ships DDS 3.6 and a user has already identified what needs to be patched to make DDS compile, see https://github.com/FairRootGroup/FairSoft/pull/492/files#diff-c9f8e4f7e9e47174062763a44864c75ae3d3c2eabfb5776c8bb45b238e51f896

Please consider adopting C++20 support with GCC and Clang in the next stable DDS release, thx!

**Comment by AnarManafov** [comment]
@dennisklein , sounds good. Will do. 
I will also make a stable release in Jan.

**Comment by AnarManafov** [comment]
Implemented and merged into the master.
The master branch now requires C++20 and builds without errors/warnings on clang 15 and gcc 13.

@dennisklein , either this week or max next week I will tag a new stable version. Just need to finish some unit-tests.

**Comment by dennisklein** [comment]
> now requires C++20

:( why do you **require** it? FairSoft and ROOT default to C++17 still.

**Comment by rbx** [comment]
Alice too: https://github.com/alisw/alidist/blob/master/defaults-o2.sh#L7

**Comment by AnarManafov** [comment]
@dennisklein and @rbx, thx. It makes sense. I will adjust it.

**Comment by AnarManafov** [comment]
Fixed in the master.
