### ISSUE TITLE
dds-commander: open several ports for example for UI, property propagation etc.

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/DDS#84]
For the moment CConnectionManagerImpl supports upto two channels: main channel and UI channel. 

Extend CConnectionManagerImpl class to be able to open several ports for incoming connections. Each communication channel must have a separate instance of boost::asio::io_service. Depending on the port io_service can use different number of threads. Threads may have priorities, for example, UI channel will have a higher priority. The number of required ports and/or their priorities and/or number of threads has to be defined by the user.

**Comment by AnarManafov** [comment]
Due to major redesign of DDS in v2.x and v3.x the issue is not relevant anymore.
